### ISSUE TITLE
Not Detecting Mobile

### ISSUE THREAD

**Issue by worshiplive** [sjelfull/craft3-mobiledetect#2]
Craft 3 (3.0.9) - Latest Mobile Detect Plugin

Using {{ craft.mobileDetect.isMobile ? 'I am mobile.' : 'I am not mobile.' }} it detects a desktop is not mobile but not when it's a mobile on my iPhone X or other devices that are mobile.

**Comment by sjelfull** [comment]
Can you look around the [MobileDetect issue tracker](https://github.com/serbanghita/Mobile-Detect/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) to see if you find any related issues?

I will update the library soon, which hopefully might fix any recent detection issues, but have no time to do any extended troubleshooting.

**Comment by sjelfull** [comment]
Actually, I just realised you should be on the latest version (2.8.31) with the current composer dependency constraint.

To reiterate: You should check MobileDetect's documentation/issues, as this plugin really just passes methods/options through to that.

**Comment by worshiplive** [comment]
My version of MobileDetect shows as MobileDetect 1.0.1

On my mobile and others mobile devices, they get nothing on desktop, they get "No Mobile".  I updated composer and still nada.

**Comment by worshiplive** [comment]
I looked through their docs, not sure what I am suppose to do here.  Do I include their library within the craft3-mobledetect folder?

**Comment by sjelfull** [comment]
No, you don't include anything manually. Its already imported.

To clarify, the version you are talking about is the Craft plugin (MobileDetect) version, 1.0.1.

My plugin uses the library [MobileDetect](https://github.com/serbanghita/Mobile-Detect) for detection, and really just passes down calls you do in Twig to the library.

That means: For any detection issues you have, you need to consult with the issues over on the MobileDetect library.

**Comment by worshiplive** [comment]
Ok cool.  I got it working with uninstalling and reinstalling  through composer, not sure why but it's working now :).

**Comment by sjelfull** [comment]
Weird - but glad that you got it working. Might have been a older version of the library.
