### ISSUE TITLE
Detection doesn't work properly

### ISSUE THREAD

**Issue by domin97** [sjelfull/craft3-mobiledetect#3]
I have a problem with detection browsers it work only in safari but not work example in Edge, Firefox and i can't find a reason. When i'm in Firefox browser mobileDetect.is('Firefox ') returns false ??

**Comment by sjelfull** [comment]
Did you try removing the space at the end of the agent string? `'Firefox'` vs. `'Firefox '`

This plugin only calls the underlying MobileDetect package - any questions regarding detection should probably be addressed there.

**Comment by domin97** [comment]
Of course that should be 'Firefox', but i have a problem because i would like to detect not only on mobile devices but also in normal browsers on pc. Is there such a possibility ? It work properly for example in google chrome if i enable in devtools mobile mode and reload page.

**Comment by sjelfull** [comment]
It shouldn't be a problem - I've done that in projects. However, user agent detection can be fickle. If you have any issues, I'd check the issues tracker on https://github.com/serbanghita/Mobile-Detect for issues that looks similar to what your having trouble with.
